### ISSUE TITLE
Branching Model and Rule

### ISSUE THREAD

**Issue by src-hyc** [Tarcadia/Fibonacci#2]
[The branching model suggested](https://github.com/Tarcadia/Fibonacci/blob/d49626469f91a71766a46a4b358944c0cd696e88/README.md?plain=1#L14) is quite weird. In most cases, any branch would have only one commit.

Also, [the Rule section](https://github.com/Tarcadia/Fibonacci/blob/d49626469f91a71766a46a4b358944c0cd696e88/README.md?plain=1#L4) seems making too much restrictions on the code, and has totally disregarded language with no variables, e.g. [Piet](https://esolangs.org/wiki/Piet).

**Comment by Mundanity-fc** [comment]
Besides, the limitation of N is, to some extents, meaningless, as the 32767th item of fibonacci sequence can be viewed as infinity, which is not easy to display and store in memory. Usually, the maximum of the index should keep in 4 digit, which means, 9999 is big enough.

**Comment by src-hyc** [comment]
Maybe we can have an orphan branch for each implementation that has its codes and docs in a folder, and merge it to main when it's done? In this manner, the feature branch doesn't have to keep track of all other implementations, and docs for each implementations can be both isolated from each other, and close to its relevant code.

**Comment by Tarcadia** [comment]
I mean, sometime it requires debug and reversion to files, so I request independent branches.

**Comment by Tarcadia** [comment]
> Maybe we can have an orphan branch for each implementation that has its codes and docs in a folder, and merge it to main when it's done? In this manner, the feature branch doesn't have to keep track of all other implementations, and docs for each implementations can be both isolated from each other, and close to its relevant code.

I think this is a good way.

**Comment by Mundanity-fc** [comment]
Then, each language builds their own branch, and requires code review. After the code review, merge the branch into the main.
